# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 1"
    }
  }
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "azure-arm" "autogenerated_1" {
  client_id                                = "AZURE_CLIENT_ID"
  client_secret                            = "AZURE_CLIENT_SECRET"
  custom_managed_image_name                = "jenkins-slave-packer-image"
  custom_managed_image_resource_group_name = "jenkins-slave-packer-rg"
  location                                 = "East US"
  managed_image_name                       = "jenkinsslave1-onprem"
  managed_image_resource_group_name        = "jenkins-terraform-azure"
  os_type                                  = "Linux"
  subscription_id                          = "AZURE_SUBSCRIPTION_ID"
  tenant_id                                = "AZURE_TENANT_ID"
  vm_size                                  = "Standard_B2ms"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.azure-arm.autogenerated_1"]

}
